[package]
name = "aspif"
version = "0.1.0"
authors = ["Sven Thiele <sthiele78@gmail.com>"]
description = "An aspif parser"
readme = "README.md"
documentation = ""
repository = "https://github.com/sthiele/aspif-parser"
publish = false
edition = "2018"

[dependencies]
nom = "7.0"